<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kim ThHCADBIDVACVDSDWEDDDAAABCKim Th_e1f2cb</name>
   <tag></tag>
   <elementGuidId>8a573619-3116-4657-8528-0e7f3bebd41f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_account_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_account_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>11728f28-8d7b-4d69-9682-189e59f7545f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>37417ac0-6e31-4e35-8b4f-0b0bf1e50d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_id</value>
      <webElementGuid>92cee401-07cb-4dcc-ad72-b237ec771b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_account_id</value>
      <webElementGuid>d9913ee2-f83d-4179-ac92-79ef060401fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cc1e1c15-eaae-4cbc-b67c-4c1424eef985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>22a957db-f53a-42e6-8fb7-63558936261f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kiểm ThửHCADBIDVACVDSDWEDDDAAABCKiểm Thử tài khoản tiết kiệmVí tiền mặt</value>
      <webElementGuid>0f0d83bc-8c95-4c2c-8ccd-8a01e2058572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_account_id&quot;)</value>
      <webElementGuid>561bca2e-9ca7-4002-b7ca-33ff436cf884</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_account_id']</value>
      <webElementGuid>786b840e-7c16-4030-b53f-dfaca23b963f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account_id_holder']/div/select</value>
      <webElementGuid>9510faba-6936-4876-a8ba-6577eb957718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lưu vào tài khoản'])[1]/following::select[1]</value>
      <webElementGuid>4b3e100e-af30-45c7-a6c6-ac3c36993a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tên'])[1]/following::select[1]</value>
      <webElementGuid>581586ed-d3ec-41b5-819d-d8b0f3e5182d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số tiền mục tiêu'])[1]/preceding::select[1]</value>
      <webElementGuid>d47d5a67-9b19-40bb-a9d8-77f111347532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Các trường tùy chọn'])[1]/preceding::select[1]</value>
      <webElementGuid>7a590b8c-7adc-41be-a6a8-c0360639dc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>839e9232-1ded-43ae-8595-fe9428d57273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account_id' and @id = 'ffInput_account_id' and (text() = 'Kiểm ThửHCADBIDVACVDSDWEDDDAAABCKiểm Thử tài khoản tiết kiệmVí tiền mặt' or . = 'Kiểm ThửHCADBIDVACVDSDWEDDDAAABCKiểm Thử tài khoản tiết kiệmVí tiền mặt')]</value>
      <webElementGuid>bde3f4d0-9b73-4b8d-9524-04d4696dc8f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
