<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ti khon mc nhti khon dng chungTi kho_88a45b</name>
   <tag></tag>
   <elementGuidId>aa83c6d7-55a0-4ee3-a05a-da9cb797cdc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_account_role</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_account_role']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ce2e82d1-2283-4f2d-815f-7006ca4f3951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1854f25f-e0fc-4191-ba03-83d1eb210afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_role</value>
      <webElementGuid>3a8d87dc-45fb-404f-811f-cd39b6d3b52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_account_role</value>
      <webElementGuid>cb1a0fe7-55e3-4850-b29a-6039b61d51a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d9a6c21f-e956-41c8-9d0d-cd34dc9e5130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ab0bbb31-382c-4157-8bdc-0897e7c39f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tài khoản mặc địnhtài khoản dùng chungTài khoản tiết kiệmThẻ tín dụngVí tiền mặt</value>
      <webElementGuid>ddef77cc-ddfd-4478-9c3d-a744b41e0732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_account_role&quot;)</value>
      <webElementGuid>9bf4f895-c4c8-4f0a-baa9-2cd64a7cf363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_account_role']</value>
      <webElementGuid>70aac1cc-d30d-4de0-8fdd-9f54711e0502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account_role_holder']/div/select</value>
      <webElementGuid>b6191cde-bca8-46d5-a701-abdfa2ce48d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vai trò tài khoản'])[1]/following::select[1]</value>
      <webElementGuid>b7a9ca05-241c-42a0-8caf-11dfbeb2f57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày mở số dư'])[1]/following::select[1]</value>
      <webElementGuid>1e6c9b23-228c-43ff-8096-0bf4d16b1952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cân bằng ảo'])[1]/preceding::select[1]</value>
      <webElementGuid>25b78079-969c-407b-9bd5-18a56bd4115b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bao gồm trong giá trị ròng'])[1]/preceding::select[1]</value>
      <webElementGuid>4a97bb8a-812d-4712-bc70-7a6b4c82571a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>0412743b-23e8-4d68-8a49-25a160f62ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account_role' and @id = 'ffInput_account_role' and (text() = 'tài khoản mặc địnhtài khoản dùng chungTài khoản tiết kiệmThẻ tín dụngVí tiền mặt' or . = 'tài khoản mặc địnhtài khoản dùng chungTài khoản tiết kiệmThẻ tín dụngVí tiền mặt')]</value>
      <webElementGuid>a1426c2b-6163-4dde-9309-4b3ad81cd6bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
