<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ti khon</name>
   <tag></tag>
   <elementGuidId>a28eca21-e510-4b33-8505-b9c9a7e691a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account-menu > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf268cfc-7309-4be5-972e-2df69d596322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tài khoản</value>
      <webElementGuid>fb5c6373-9003-4330-ae62-acaac49d400d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-menu&quot;)/a[1]/span[1]</value>
      <webElementGuid>c6d0eabe-2103-438f-a4d3-e88b091e9e6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='account-menu']/a/span</value>
      <webElementGuid>831b3af3-bf8c-45b6-a0fa-e56e6c6fea6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khác'])[1]/following::span[1]</value>
      <webElementGuid>aacfd1f8-4093-4618-9caf-9d717c7ca588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Webhooks'])[1]/following::span[1]</value>
      <webElementGuid>b5cb1439-a25e-430c-8e2b-aa909a5f840f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tài khoản'])[1]/preceding::span[4]</value>
      <webElementGuid>81c299de-a1b2-4110-a9f7-fbc7f18d772b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản chi phí'])[1]/preceding::span[6]</value>
      <webElementGuid>63f16bff-4afb-4ed1-bb35-88a492198af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a/span</value>
      <webElementGuid>3249723e-aea9-457f-ab35-12465e7a7a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tài khoản' or . = 'Tài khoản')]</value>
      <webElementGuid>85cc846a-56d3-4efa-b242-9434cbac7caa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
