<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cn li (mi ngy)_fa fa-fw fa-trash-o</name>
   <tag></tag>
   <elementGuidId>ea04d3b8-3fd8-4027-9de6-46ad30789c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw.fa-trash-o</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='budgetList']/tbody/tr/td/div/a[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a19be228-64be-4899-ab7e-7cd8944f50f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-trash-o</value>
      <webElementGuid>3849d26d-5f64-4f30-8b91-5e9e5af000cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;budgetList&quot;)/tbody[@class=&quot;ui-sortable&quot;]/tr[1]/td[@class=&quot;hidden-sm hidden-xs&quot;]/div[@class=&quot;btn-group btn-group-xs&quot;]/a[@class=&quot;btn btn-xs btn-danger&quot;]/span[@class=&quot;fa fa-fw fa-trash-o&quot;]</value>
      <webElementGuid>196599a9-62ec-48fe-869e-36761cf425ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='budgetList']/tbody/tr/td/div/a[3]/span</value>
      <webElementGuid>5f49fa15-2431-477e-a37b-abc7492d351a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>e35c4588-b4c4-4d7e-98da-a170cbf13291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
