<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Khng c ngn sch t ngt s tin c nh mi k_d49eb4</name>
   <tag></tag>
   <elementGuidId>274d11f4-2365-4e63-9a56-fd632355e78c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_auto_budget_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_auto_budget_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>05377f79-3fa1-419a-9ebe-14dcdbd3c329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f5bdabd1-7dec-4ad0-947e-14bf1d5a2d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>auto_budget_type</value>
      <webElementGuid>070df30c-9fc1-448a-8182-2134d26cecc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_auto_budget_type</value>
      <webElementGuid>868104e1-448f-4061-8a06-46a502276c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5d428e93-6a8a-4717-b9ce-fc829c3da139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f23ac8b5-1df7-4bb7-b2a2-82328013a97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Không có ngân sách tự độngĐặt số tiền cố định mỗi kỳThêm một số tiền mỗi kỳAdd an amount every period and correct for overspending</value>
      <webElementGuid>484109f1-e346-476f-b15a-333929410da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_auto_budget_type&quot;)</value>
      <webElementGuid>49099378-c5e1-46ea-bc13-191ee8641883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_auto_budget_type']</value>
      <webElementGuid>78b9c8ed-bf7d-4694-9736-2d73b0fe2d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auto_budget_type_holder']/div/select</value>
      <webElementGuid>a9954c87-ac0e-4bc1-90ee-57408cbc4f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngân sách tự động'])[1]/following::select[1]</value>
      <webElementGuid>662f5982-9c41-4b59-a161-75e3f8f62fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Các trường tùy chọn'])[1]/following::select[1]</value>
      <webElementGuid>fd60dba0-1062-4813-b545-74d876a0215d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiền tệ'])[2]/preceding::select[1]</value>
      <webElementGuid>53544cda-3256-4a00-ac05-6fa3468ae800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số tiền ngân sách tự động'])[1]/preceding::select[2]</value>
      <webElementGuid>5c47e548-500d-427d-ad8d-9b7abff34bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d17c123e-7480-4fa7-b73c-2f0092e9965c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'auto_budget_type' and @id = 'ffInput_auto_budget_type' and (text() = ' Không có ngân sách tự độngĐặt số tiền cố định mỗi kỳThêm một số tiền mỗi kỳAdd an amount every period and correct for overspending' or . = ' Không có ngân sách tự độngĐặt số tiền cố định mỗi kỳThêm một số tiền mỗi kỳAdd an amount every period and correct for overspending')]</value>
      <webElementGuid>9dd79473-d756-42e3-803c-86ab0e5baa68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
