<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Euro ()US Dollar ()</name>
   <tag></tag>
   <elementGuidId>16886b9c-40c1-4cf7-9aa7-52d5876089b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_auto_budget_currency_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_auto_budget_currency_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e0af486f-e30e-4ca6-b6dd-bbc419d4e797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5c755137-9679-44d5-abb3-1f4b39d72305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>auto_budget_currency_id</value>
      <webElementGuid>000ff8e3-2fa2-4e1e-962e-25331b1f27f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_auto_budget_currency_id</value>
      <webElementGuid>857f25d2-050d-4025-a2b1-bf7d3e34eecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>753f0ac7-8c7a-4660-ba27-a40804e8c762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>389c160b-841d-429e-83a0-8f0b96afebca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Euro (€)US Dollar ($)</value>
      <webElementGuid>3d36836a-dfb8-4494-9034-d404faad489e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_auto_budget_currency_id&quot;)</value>
      <webElementGuid>726d4a1c-7197-4abf-bcee-babe9b4d63ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_auto_budget_currency_id']</value>
      <webElementGuid>14a1f11b-d7e4-4b01-ac4c-27c94925c5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auto_budget_currency_id_holder']/div/select</value>
      <webElementGuid>e56f7829-425d-4e3a-8652-277151f19cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiền tệ'])[2]/following::select[1]</value>
      <webElementGuid>d9ea8b0b-9d61-4c97-a81a-eae98fd3f90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngân sách tự động'])[1]/following::select[2]</value>
      <webElementGuid>70a6ef1a-06d9-4299-bd1c-51e9140f6677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số tiền ngân sách tự động'])[1]/preceding::select[1]</value>
      <webElementGuid>9eb4a07d-cebe-45c1-b23a-aeb1b843abdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chu kỳ ngân sách tự động'])[1]/preceding::select[1]</value>
      <webElementGuid>926e9f5b-2482-41a9-ba96-c9075712f8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>e7a3d25b-4315-47b4-afd7-0df4fc3e1034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'auto_budget_currency_id' and @id = 'ffInput_auto_budget_currency_id' and (text() = 'Euro (€)US Dollar ($)' or . = 'Euro (€)US Dollar ($)')]</value>
      <webElementGuid>08188e7f-02d8-4dd0-b9d2-3d06cf202039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
