<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Hng ngyHng tunHng thngHng quMi na nmHng nm</name>
   <tag></tag>
   <elementGuidId>ab19d904-849b-40ba-b398-73b7efd24a0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_auto_budget_period']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_auto_budget_period</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>926fd618-6996-4761-be5b-7a508ee0e7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e83d1688-984e-4fd5-b28b-abee0925c970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>auto_budget_period</value>
      <webElementGuid>36e2b3ad-1fbc-4916-b04f-8ca7237fab85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_auto_budget_period</value>
      <webElementGuid>bf07443e-d4f2-4002-97aa-ab8d2efe44c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d39e3b9b-99de-428b-8c5a-0609af5d7c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3dd834ac-780f-444b-a1e3-23813ba83603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hàng ngàyHàng tuầnHàng thángHàng quýMỗi nửa nămHàng năm</value>
      <webElementGuid>00ce956a-2880-4009-a010-90bc489fb337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_auto_budget_period&quot;)</value>
      <webElementGuid>38450cdc-488b-4c74-b2c6-e9f9f7aa68f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_auto_budget_period']</value>
      <webElementGuid>100b30c8-d611-415c-a41a-3eb9fe1fb2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auto_budget_period_holder']/div/select</value>
      <webElementGuid>fbd5d157-2249-4a59-96bc-d649fa43b58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chu kỳ ngân sách tự động'])[1]/following::select[1]</value>
      <webElementGuid>95e70114-96db-4871-b5aa-fb11aee2739e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số tiền ngân sách tự động'])[1]/following::select[1]</value>
      <webElementGuid>5ed26a15-fe7a-41f1-b1d3-2bca04b3549a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài liệu đính kèm'])[1]/preceding::select[1]</value>
      <webElementGuid>3efc8b64-26de-4f4f-a224-3b8b0d29c748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tùy chọn'])[2]/preceding::select[1]</value>
      <webElementGuid>e2eade11-dfa4-424d-9d53-797d7905ff46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>fb0573f4-cd53-4013-afe4-eedc1210aa55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'auto_budget_period' and @id = 'ffInput_auto_budget_period' and (text() = 'Hàng ngàyHàng tuầnHàng thángHàng quýMỗi nửa nămHàng năm' or . = 'Hàng ngàyHàng tuầnHàng thángHàng quýMỗi nửa nămHàng năm')]</value>
      <webElementGuid>3b7a9a95-e229-438d-b7ce-56e22fde364b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
