<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Trng)      ATUU      FZET      HNMY_dea5ed</name>
   <tag></tag>
   <elementGuidId>40f94f63-8a60-42e1-9902-6a1a7433ecfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;bill[]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f795c756-5a78-4a85-8e0d-272693443386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hóa đơn</value>
      <webElementGuid>efe0d720-fdd0-4bfd-9da3-5532e02b3a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill[]</value>
      <webElementGuid>22e188e2-99f0-4165-a0b1-4467f2e6da28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a2c96752-cebb-480a-b02c-a1c1d8a6bff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(Trống)
      ATUU
      FZET
      HNMY
      IMYK
      PVBJ
      PWEY
      RDSQ
      SSJF
      VPXR
      </value>
      <webElementGuid>40d434fa-8db0-4a6c-a2fa-33475a6694c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optional-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>e6953e83-af13-4060-836b-f2faa2479232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='bill[]']</value>
      <webElementGuid>4fde27c9-e7d2-4009-a3ed-0af3718e4bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div[5]/div[2]/select</value>
      <webElementGuid>1a05b6a8-386c-4251-885b-61427f8ce99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hóa đơn'])[2]/following::select[1]</value>
      <webElementGuid>2f4b65df-4b11-4d6f-9a0c-38ee3b4b4e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhãn'])[2]/following::select[1]</value>
      <webElementGuid>14c7933e-8125-491a-b6d4-bb7ed4dd378e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='preferences'])[1]/preceding::select[1]</value>
      <webElementGuid>d12faaf0-4b48-462c-82c3-3d7e09910eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày lãi'])[1]/preceding::select[1]</value>
      <webElementGuid>9077fb56-505b-4295-92fa-fab3818e84f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/select</value>
      <webElementGuid>8c04a391-774e-4997-8fc7-fbe213f8ba69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Hóa đơn' and @name = 'bill[]' and (text() = '(Trống)
      ATUU
      FZET
      HNMY
      IMYK
      PVBJ
      PWEY
      RDSQ
      SSJF
      VPXR
      ' or . = '(Trống)
      ATUU
      FZET
      HNMY
      IMYK
      PVBJ
      PWEY
      RDSQ
      SSJF
      VPXR
      ')]</value>
      <webElementGuid>a431de67-53ad-4ac5-955b-1c27a84b39f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
