<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ti khon</name>
   <tag></tag>
   <elementGuidId>82bbcc71-a153-49a3-afb5-09abdc4955dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='account-menu']/ul/li/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1f2e1262-37a3-43b1-aa8b-ab3e4d950962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tài khoản</value>
      <webElementGuid>ae6a59d5-4b9a-4f85-b2c5-60de1e81a979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-menu&quot;)/ul[@class=&quot;treeview-menu&quot;]/li[1]/a[1]/span[2]</value>
      <webElementGuid>bd1b58f4-016b-45c2-8755-dab951728e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='account-menu']/ul/li/a/span[2]</value>
      <webElementGuid>023620dd-e163-42ed-aab7-43e13fb11e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản'])[2]/following::span[4]</value>
      <webElementGuid>44ae6e3f-eeab-4a74-895c-04d688986e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khác'])[1]/following::span[5]</value>
      <webElementGuid>244f6141-ff7f-4c1a-83c4-15f68c65c356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản chi phí'])[1]/preceding::span[2]</value>
      <webElementGuid>7b0b1010-52d8-4ba7-9f5e-2cfd97f54a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản doanh thu'])[1]/preceding::span[4]</value>
      <webElementGuid>13e72f91-1026-4772-930d-45788b5888fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tài khoản']/parent::*</value>
      <webElementGuid>bbd8d663-8c05-45aa-b082-6bf5217f7796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/ul/li/a/span[2]</value>
      <webElementGuid>d72659f2-55df-4364-adad-2277777367a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'tài khoản' or . = 'tài khoản')]</value>
      <webElementGuid>68521bef-8b43-460d-b6b1-afbca970a407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='account-menu']/a/span</value>
      <webElementGuid>f04afd2f-87b0-45cc-b7f7-9b949f8846dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khác'])[1]/following::span[1]</value>
      <webElementGuid>267ab2d8-adb6-4aff-a3d5-c006d2a6cdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Webhooks'])[1]/following::span[1]</value>
      <webElementGuid>ffed8166-5a43-4cec-8f56-9ea71c9c04d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tài khoản'])[1]/preceding::span[4]</value>
      <webElementGuid>d100f0de-ea86-46a9-b258-0fa14630274a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản chi phí'])[1]/preceding::span[6]</value>
      <webElementGuid>6456b1ba-f585-47ed-83cf-e0817fccd1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a/span</value>
      <webElementGuid>cdc74cd2-da24-4e94-80a9-8054567751b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tài khoản' or . = 'Tài khoản')]</value>
      <webElementGuid>76fc444b-eb5f-4882-a437-5e461ddbe1d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
