<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_hng ngyhng tunhng thnghng qumi na nmhng nm</name>
   <tag></tag>
   <elementGuidId>fc1c4769-97e5-43c7-9d6a-599e682c96b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_repeat_freq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_repeat_freq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fd661294-1383-45f4-81d0-e011842c7539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3135721c-935b-40f3-baa6-6e844c972f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeat_freq</value>
      <webElementGuid>e92983ba-b6ab-49d4-abfe-badf4e3e8b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_repeat_freq</value>
      <webElementGuid>a47d39cb-b872-458c-a053-c72099f3b75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>04152a73-9db4-48b3-b942-7f28c7874d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2e518b3-01b0-40ac-91c6-01fb5c830512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hằng ngàyhàng tuầnhàng thánghàng quýmỗi nửa nămhàng năm</value>
      <webElementGuid>e292699e-65c8-49d2-b27d-e17e0467f95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_repeat_freq&quot;)</value>
      <webElementGuid>9af0359b-5f4f-4934-8a0d-39818cb04e72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_repeat_freq']</value>
      <webElementGuid>6f616542-0d71-48bb-a6e7-dbd04a836d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeat_freq_holder']/div/select</value>
      <webElementGuid>9b400852-c706-4f33-9dd8-1a678f6f2e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lặp lại'])[1]/following::select[1]</value>
      <webElementGuid>ac81a1ed-5a1b-46bb-a95d-4ef635cfc7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày'])[1]/following::select[1]</value>
      <webElementGuid>cc5cf8ae-ffbc-4e44-b355-6f3cb0a62644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ qua'])[1]/preceding::select[1]</value>
      <webElementGuid>d91d9627-0855-4c07-8de5-a5f3e7054bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Các trường tùy chọn'])[1]/preceding::select[1]</value>
      <webElementGuid>45def63e-8889-4d2c-9ffb-dc108758d788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>5398b1a8-bba8-4af9-bffb-2a0277655ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'repeat_freq' and @id = 'ffInput_repeat_freq' and (text() = 'hằng ngàyhàng tuầnhàng thánghàng quýmỗi nửa nămhàng năm' or . = 'hằng ngàyhàng tuầnhàng thánghàng quýmỗi nửa nămhàng năm')]</value>
      <webElementGuid>11695a54-f8ff-409c-925c-23ddea382c2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
