<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>6a042033-7801-46b9-b7bb-d122e63ffc57</testSuiteGuid>
   <testCaseLink>
      <guid>c09206c7-fe05-4021-b68b-2e658b681837</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_account</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>00a6d328-04f9-42ef-b518-2c5bec15e142</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_account</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>00a6d328-04f9-42ef-b518-2c5bec15e142</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>6a0c0eb6-5c81-47d0-a885-4df9b86ca8e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f39c086-23e5-4510-aaba-4f44ccd737f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8df7b067-9042-495d-b5ac-409d5a2f1e2b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
